In [ ]:
import numpy as np
import gymnasium as gym
import random
import time
from IPython.display import clear_output

In [ ]:
env = gym.make('FrozenLake-v1', render_mode='ansi')

In [ ]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [ ]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01

In [ ]:
rewards_all_episodes = []

In [ ]:
# Q-learning algorithm

for episode in range(num_episodes):
    state = env.reset()[0]
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):
      # Exploration-exploitation trade-off
      exploration_rate_threshold = random.uniform(0, 1)
      if exploration_rate_threshold > exploration_rate:
        action = np.argmax(q_table[state,:])
      else:
        action = env.action_space.sample()
      new_state, reward, done, truncated, info = env.step(action)
    # Update Q-table for Q(s,a)
      q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
        learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
      state = new_state
      rewards_current_episode += reward
      if done == True:
        break
  # Exploration rate decay
    exploration_rate = min_exploration_rate + \
      (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
rewards_all_episodes.append(rewards_current_episode)
#rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
rewards_per_thousand_episodes = np.array_split(np.array(rewards_all_episodes), num_episodes / 1000)
count = 1000
print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
  print(count, ": ", str(sum(r/1000)))
  count += 1000
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Average reward per thousand episodes********

1000 :  0.0
2000 :  0.001
3000 :  0
4000 :  0
5000 :  0
6000 :  0
7000 :  0
8000 :  0
9000 :  0
10000 :  0


********Q-table********

[[0.56229335 0.48868513 0.48503137 0.47540776]
 [0.11287676 0.18484418 0.16809226 0.43953491]
 [0.36173185 0.20830206 0.23751782 0.30964172]
 [0.09254382 0.08913649 0.07470109 0.28485438]
 [0.59568036 0.19537349 0.45895349 0.47556547]
 [0.         0.         0.         0.        ]
 [0.32910792 0.16710009 0.16681114 0.16516767]
 [0.         0.         0.         0.        ]
 [0.34367664 0.39009902 0.46122965 0.65059529]
 [0.49481237 0.68819779 0.39552977 0.35401881]
 [0.68512846 0.44409841 0.43707461 0.28000272]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.55306419 0.59846356 0.78585645 0.4240859 ]
 [0.7078813  0.93384597 0.73197183 0.73134935]
 [0.         0.         0.         0.        ]]


In [ ]:
for episode in range(3):
    state = env.reset()[0]
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)
    for step in range(max_steps_per_episode):
      clear_output(wait=True)
      print(env.render())
      time.sleep(0.3)

      action = np.argmax(q_table[state,:])
      new_state, reward, done, truncated, info = env.step(action)
      if done:
        clear_output(wait=True)
        print(env.render())
        if reward == 1:
          print("****You reached the goal!****")
          time.sleep(3)
        else:
          print("****You fell through a hole!****")
          time.sleep(3)
          clear_output(wait=True)
        break
      state = new_state
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG

****You reached the goal!****
